-- 0009 — Valutazioni in stile Football Manager
-- Sostituisce i 71 rating precedenti con il set FM (47 attributi):
--   Tecnica (14) · Psicologia (14) · Fisico (8) · Portiere (11).
-- Scala invariata: interi 1-10 (CHECK BETWEEN 1 AND 10).
-- NB: le valutazioni dei giocatori esistenti vengono azzerate (colonne nuove = NULL).
--     Anagrafica, contratto, influenze e domande comportamentali restano intatti.

-- 1) Drop dei 71 rating legacy ------------------------------------------------
ALTER TABLE players
  -- Comportamentali (14)
  DROP COLUMN IF EXISTS behav_carisma,
  DROP COLUMN IF EXISTS behav_autostima,
  DROP COLUMN IF EXISTS behav_personalita,
  DROP COLUMN IF EXISTS behav_spirito_sacrificio,
  DROP COLUMN IF EXISTS behav_spirito_comprensione,
  DROP COLUMN IF EXISTS behav_generosita,
  DROP COLUMN IF EXISTS behav_aggressivita,
  DROP COLUMN IF EXISTS behav_autocritica,
  DROP COLUMN IF EXISTS behav_spirito_collaborativo,
  DROP COLUMN IF EXISTS behav_atteggiamento_in_campo,
  DROP COLUMN IF EXISTS behav_atteggiamento_fuori_campo,
  DROP COLUMN IF EXISTS behav_concentrazione,
  DROP COLUMN IF EXISTS behav_temperamento,
  DROP COLUMN IF EXISTS behav_tenacia,
  -- Atletiche (12)
  DROP COLUMN IF EXISTS atl_velocita_senza_palla,
  DROP COLUMN IF EXISTS atl_accelerazione,
  DROP COLUMN IF EXISTS atl_cambi_direzione,
  DROP COLUMN IF EXISTS atl_elevazione,
  DROP COLUMN IF EXISTS atl_resistenza_fatica,
  DROP COLUMN IF EXISTS atl_flessibilita,
  DROP COLUMN IF EXISTS atl_rapidita,
  DROP COLUMN IF EXISTS atl_agilita,
  DROP COLUMN IF EXISTS atl_cambio_passo,
  DROP COLUMN IF EXISTS atl_forza,
  DROP COLUMN IF EXISTS atl_potenza_contrasti,
  DROP COLUMN IF EXISTS atl_abilita_acrobatica,
  -- Tecnica legacy (8)
  DROP COLUMN IF EXISTS tec_lato_dominante,
  DROP COLUMN IF EXISTS tec_piede_dx,
  DROP COLUMN IF EXISTS tec_piede_sx,
  DROP COLUMN IF EXISTS tec_gioco_testa,
  DROP COLUMN IF EXISTS tec_ricezione_piede,
  DROP COLUMN IF EXISTS tec_ricezione_petto,
  DROP COLUMN IF EXISTS tec_trasmissione_piede,
  DROP COLUMN IF EXISTS tec_trasmissione_testa,
  -- Coordinative (8)
  DROP COLUMN IF EXISTS coord_equilibrio,
  DROP COLUMN IF EXISTS coord_differenziazione,
  DROP COLUMN IF EXISTS coord_ritmizzazione,
  DROP COLUMN IF EXISTS coord_orientamento,
  DROP COLUMN IF EXISTS coord_reazione,
  DROP COLUMN IF EXISTS coord_accoppiamento_motorio,
  DROP COLUMN IF EXISTS coord_adattamento,
  DROP COLUMN IF EXISTS coord_anticipazione,
  -- Tattica individuale possesso (13)
  DROP COLUMN IF EXISTS tatti_poss_visione_periferica,
  DROP COLUMN IF EXISTS tatti_poss_smarcamento,
  DROP COLUMN IF EXISTS tatti_poss_controllo_difesa_palla,
  DROP COLUMN IF EXISTS tatti_poss_dribbling,
  DROP COLUMN IF EXISTS tatti_poss_occupazione_spazio,
  DROP COLUMN IF EXISTS tatti_poss_taglio,
  DROP COLUMN IF EXISTS tatti_poss_sovrapposizione,
  DROP COLUMN IF EXISTS tatti_poss_triangolazione,
  DROP COLUMN IF EXISTS tatti_poss_finta,
  DROP COLUMN IF EXISTS tatti_poss_falli_laterali,
  DROP COLUMN IF EXISTS tatti_poss_fantasia_estro,
  DROP COLUMN IF EXISTS tatti_poss_vedere_porta,
  DROP COLUMN IF EXISTS tatti_poss_agisce_stile,
  -- Tattica individuale non possesso (8)
  DROP COLUMN IF EXISTS tatti_nposs_marcamento,
  DROP COLUMN IF EXISTS tatti_nposs_pressione,
  DROP COLUMN IF EXISTS tatti_nposs_anticipo,
  DROP COLUMN IF EXISTS tatti_nposs_intercettamento,
  DROP COLUMN IF EXISTS tatti_nposs_contrasto_diretto,
  DROP COLUMN IF EXISTS tatti_nposs_difesa_zona,
  DROP COLUMN IF EXISTS tatti_nposs_ripresa_fine_azione,
  DROP COLUMN IF EXISTS tatti_nposs_ripresa_dopo_perdita,
  -- Tattica applicata (8)
  DROP COLUMN IF EXISTS tappl_poss_lettura_veloce,
  DROP COLUMN IF EXISTS tappl_poss_fantasia_gioco,
  DROP COLUMN IF EXISTS tappl_poss_velocita_esecuzione,
  DROP COLUMN IF EXISTS tappl_nposs_scalare,
  DROP COLUMN IF EXISTS tappl_nposs_pressing,
  DROP COLUMN IF EXISTS tappl_nposs_partecipazione_difensiva,
  DROP COLUMN IF EXISTS tappl_nposs_anticipazione_gioco,
  DROP COLUMN IF EXISTS tappl_ruolo_comportamento;

-- 2) Nuovi attributi FM (47), interi 1-10 ------------------------------------
ALTER TABLE players
  -- Tecnica (14)
  ADD COLUMN IF NOT EXISTS tec_colpi_testa     SMALLINT CHECK (tec_colpi_testa     BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS tec_contrasti       SMALLINT CHECK (tec_contrasti       BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS tec_controllo_palla SMALLINT CHECK (tec_controllo_palla BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS tec_cross           SMALLINT CHECK (tec_cross           BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS tec_dribbling       SMALLINT CHECK (tec_dribbling       BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS tec_finalizzazione  SMALLINT CHECK (tec_finalizzazione  BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS tec_marcatura       SMALLINT CHECK (tec_marcatura       BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS tec_passaggi        SMALLINT CHECK (tec_passaggi        BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS tec_tecnica         SMALLINT CHECK (tec_tecnica         BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS tec_tiri_lontano    SMALLINT CHECK (tec_tiri_lontano    BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS tec_calci_angolo    SMALLINT CHECK (tec_calci_angolo    BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS tec_punizioni       SMALLINT CHECK (tec_punizioni       BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS tec_rigori          SMALLINT CHECK (tec_rigori          BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS tec_rimesse_lunghe  SMALLINT CHECK (tec_rimesse_lunghe  BETWEEN 1 AND 10),
  -- Psicologia (14)
  ADD COLUMN IF NOT EXISTS men_aggressivita    SMALLINT CHECK (men_aggressivita    BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS men_carisma         SMALLINT CHECK (men_carisma         BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS men_concentrazione  SMALLINT CHECK (men_concentrazione  BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS men_coraggio        SMALLINT CHECK (men_coraggio        BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS men_decisioni       SMALLINT CHECK (men_decisioni       BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS men_determinazione  SMALLINT CHECK (men_determinazione  BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS men_fantasia        SMALLINT CHECK (men_fantasia        BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS men_freddezza       SMALLINT CHECK (men_freddezza       BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS men_gioco_squadra   SMALLINT CHECK (men_gioco_squadra   BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS men_impegno         SMALLINT CHECK (men_impegno         BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS men_intuito         SMALLINT CHECK (men_intuito         BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS men_posizione       SMALLINT CHECK (men_posizione       BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS men_senza_palla     SMALLINT CHECK (men_senza_palla     BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS men_visione         SMALLINT CHECK (men_visione         BETWEEN 1 AND 10),
  -- Fisico (8)
  ADD COLUMN IF NOT EXISTS fis_accelerazione   SMALLINT CHECK (fis_accelerazione   BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS fis_agilita         SMALLINT CHECK (fis_agilita         BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS fis_equilibrio      SMALLINT CHECK (fis_equilibrio      BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS fis_forza           SMALLINT CHECK (fis_forza           BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS fis_integrita       SMALLINT CHECK (fis_integrita       BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS fis_elevazione      SMALLINT CHECK (fis_elevazione      BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS fis_resistenza      SMALLINT CHECK (fis_resistenza      BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS fis_velocita        SMALLINT CHECK (fis_velocita        BETWEEN 1 AND 10),
  -- Portiere (11)
  ADD COLUMN IF NOT EXISTS gk_gioco_aereo      SMALLINT CHECK (gk_gioco_aereo      BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS gk_comando_area     SMALLINT CHECK (gk_comando_area     BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS gk_comunicazione    SMALLINT CHECK (gk_comunicazione    BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS gk_eccentricita     SMALLINT CHECK (gk_eccentricita     BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS gk_presa            SMALLINT CHECK (gk_presa            BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS gk_rinvio           SMALLINT CHECK (gk_rinvio           BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS gk_uno_vs_uno       SMALLINT CHECK (gk_uno_vs_uno       BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS gk_riflessi         SMALLINT CHECK (gk_riflessi         BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS gk_tendenza_uscire  SMALLINT CHECK (gk_tendenza_uscire  BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS gk_tendenza_pugni   SMALLINT CHECK (gk_tendenza_pugni   BETWEEN 1 AND 10),
  ADD COLUMN IF NOT EXISTS gk_lancio           SMALLINT CHECK (gk_lancio           BETWEEN 1 AND 10);
